// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Data;

#nullable disable

namespace MyBudget.Migrations
{
    [DbContext(typeof(AppMyBudgetContext))]
    [Migration("20260901163727_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MyBudget.Models.ClassOfAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubGroupId");

                    b.ToTable("ClassesOfAccount");
                });

            modelBuilder.Entity("MyBudget.Models.GroupOfAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupInformation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupOfAccounts");
                });

            modelBuilder.Entity("MyBudget.Models.SubGroupOfAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubGroupDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("SubGroupOfAccounts");
                });

            modelBuilder.Entity("MyBudget.Models.ClassOfAccounts", b =>
                {
                    b.HasOne("MyBudget.Models.SubGroupOfAccounts", "SubGroupOfAccounts")
                        .WithMany("ClassesOfAccounts")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubGroupOfAccounts");
                });

            modelBuilder.Entity("MyBudget.Models.SubGroupOfAccounts", b =>
                {
                    b.HasOne("MyBudget.Models.GroupOfAccounts", "GroupOfAccounts")
                        .WithMany("SubGroupsOfAccounts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupOfAccounts");
                });

            modelBuilder.Entity("MyBudget.Models.GroupOfAccounts", b =>
                {
                    b.Navigation("SubGroupsOfAccounts");
                });

            modelBuilder.Entity("MyBudget.Models.SubGroupOfAccounts", b =>
                {
                    b.Navigation("ClassesOfAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
